run:
  deadline: 120s
  tests: false

linters:
  enable-all: true
  disable:
    - gocyclo
    - gofmt
    - gomnd # extremely aggressive linter that complains about all numeric literals, even just adding 1 to something (https://github.com/tommy-muehle/go-mnd)
    - maligned
    - unparam
    - lll
  fast: false

linter-settings:
  gofmt:
    simplify: false

issues:
  exclude:
    - "(func|method|struct field|type|var) .* should be " # golint errors about variable names (don't want to fix them because they're in a public interface)
    - "G104: Errors unhandled." # Let errcheck handle these
  exclude-use-default: false
  max-same-issues: 1000
  max-per-linter: 1000
