run:
  deadline: 120s
  tests: false

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dupl
    - errcheck
    - goconst
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    #- gofmt  # temporarily disabled because it will require many whitespace fixes
    #- goimports  # temporarily disabled because it flags the same whitespace issues as gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
  fast: false

linters-settings:
  gofmt:
    simplify: false
  goimports:
    local-prefixes: gopkg.in/launchdarkly,github.com/launchdarkly
  
issues:
  exclude-use-default: false
  max-same-issues: 1000
  max-per-linter: 1000
