version: 2.1

workflows:
  workflow:
    jobs:
      - go-test:
          name: Go 1.13
          docker-image: circleci/golang:1.12
      - go-test:
          name: Go 1.12
          docker-image: circleci/golang:1.12
          # We can't run the linter in Go 1.12 because of a known issue with build tags not working correctly
          # in golangci-lint; the linter uses the build tags that *the linter* was built with, rather than the
          # current environment, and there's some Go 1.12 library code that relies on build tags.
          run-lint: false
      - go-test:
          name: Go 1.11
          docker-image: circleci/golang:1.11
      - go-test:
          name: Go 1.10
          docker-image: circleci/golang:1.10
      - go-test:
          name: Go 1.9
          docker-image: circleci/golang:1.9
      - go-test:
          name: Go 1.8
          docker-image: circleci/golang:1.8

jobs:
  go-test:
    parameters:
      run-lint:
        type: boolean
        default: true
      docker-image:
        type: string

    docker:
      - image: <<parameters.docker-image>>
        environment:
          CIRCLE_TEST_REPORTS: /tmp/circle-reports
          CIRCLE_ARTIFACTS: /tmp/circle-artifacts
          COMMON_GO_PACKAGES: >
            github.com/golang/dep/cmd/dep
            github.com/jstemmer/go-junit-report
      - image: redis
      - image: consul
      - image: amazon/dynamodb-local

    steps:
      - checkout
      - run: go get -u $COMMON_GO_PACKAGES
      - when:
          condition: <<parameters.run-lint>>
          steps:
            - run: npm run lint
      - run: dep ensure -dry-run
      - run: go build ./...
      
      - run:
          name: Run tests
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS
            mkdir -p $CIRCLE_ARTIFACTS
            trap "go-junit-report < $CIRCLE_ARTIFACTS/report.txt > $CIRCLE_TEST_REPORTS/junit.xml" EXIT
            make test | tee $CIRCLE_ARTIFACTS/report.txt

      - store_test_results:
          path: /tmp/circle-reports

      - store_artifacts:
          path: /tmp/circle-artifacts
