version: 2

experimental:
  notify:
    branches:
      only:
        - master
        - v2
        - v3
        - v4

defaults:
  environment: &environment
    CIRCLE_TEST_REPORTS: /tmp/circle-reports
    CIRCLE_ARTIFACTS: /tmp/circle-artifacts
    COMMON_GO_PACKAGES: >
      github.com/golang/dep/cmd/dep
      github.com/jstemmer/go-junit-report
      github.com/kyoh86/richgo

  build_steps: &build_steps
    steps:
      - checkout
      - run: go get -u $COMMON_GO_PACKAGES
      - run: make lint
      - run: dep ensure -dry-run

      - run:
          name: Run tests
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS
            mkdir -p $CIRCLE_ARTIFACTS
            trap "go-junit-report < $CIRCLE_ARTIFACTS/report.txt > $CIRCLE_TEST_REPORTS/junit.xml" EXIT
            make test | tee >(richgo testfilter) > $CIRCLE_ARTIFACTS/report.txt

      - store_test_results:
          path: /tmp/circle-reports

      - store_artifacts:
          path: /tmp/circle-artifacts

jobs:
  go-test:
    working_directory: /go/src/gopkg.in/launchdarkly/go-server-sdk.v4

    docker:
      - image: circleci/golang:1.10.1
        environment:
          <<: *environment
      - image: redis
      - image: consul
      - image: amazon/dynamodb-local

    <<: *build_steps

  go-test-1.9:
    working_directory: /go/src/gopkg.in/launchdarkly/go-server-sdk.v4

    docker:
      - image: circleci/golang:1.9
        environment:
          <<: *environment
      - image: redis
      - image: consul
      - image: amazon/dynamodb-local

    <<: *build_steps

  go-test-1.8:
    working_directory: /go/src/gopkg.in/launchdarkly/go-server-sdk.v4

    docker:
      - image: circleci/golang:1.8
        environment:
          <<: *environment
      - image: redis
      - image: consul
      - image: amazon/dynamodb-local

    <<: *build_steps

workflows:
  version: 2
  test:
    jobs:
      - go-test
      - go-test-1.9
      - go-test-1.8
