version: 2

repo:
  public: go-server-sdk
  private: go-server-sdk-private

branches:
  - name: v6
  - name: v5
  - name: v4

jobs:
  - docker:
      image: golang:1.16-buster
    template:
      name: go
    env:
      LD_RELEASE_GO_IMPORT_PATH: gopkg.in/launchdarkly/go-server-sdk.v6

publications:
  - url: https://pkg.go.dev/gopkg.in/launchdarkly/go-server-sdk.v6
    description: documentation

sdk:
  displayName: "Go"
